# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Validate changes

on: push
  # push:
  #   branches: ["main"]
  # pull_request:
  #   branches: ["main"]

permissions:
  contents: read

env:
  ZEPHYR_TOKEN: ${{ secrets.ZEPHYR_TOKEN }}
  JIRA_PAT: ${{ secrets.JIRA_PAT }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@9db7f66e8e16b5699a514448ce994936c63f0d54
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno task check

      - name: Validate changes
        run: deno task validate

      - name: Save changes
        run: deno task save

      - name: Sync changes
        run: deno task sync

      - name: Commit changes
        if: github.event_name == 'push'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add .
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push