name: Validate changes

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  ZEPHYR_TOKEN: ${{ secrets.ZEPHYR_TOKEN }}
  JIRA_PAT: ${{ secrets.JIRA_PAT }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno task check

      - name: Validate changes
        run: deno task validate

      - name: Save changes
        if: ${{ github.event_name == 'pull_request' && github.ref == 'refs/heads/add_actions' }}
        run: deno task save

      - name: Sync changes
        if: ${{ github.event_name == 'pull_request' && github.ref == 'refs/heads/add_actions' }}
        run: deno task sync

      - name: Run if changes have been detected
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "Changes!"

      - name: Run if no changes have been detected
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No Changes!"

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ github.event_name == 'pull_request' && github.ref == 'refs/heads/add_actions' }}
        with:
          commit_message: "chore(data): Sync"
          add_options: '-u'
          skip_dirty_check: true

      # - name: Commit changes
      #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/add_actions' }}
      #   run: |
      #     git config user.name "GitHub Actions Bot"
      #     git config user.email "<>"
      #     git add .
      #     git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
      #     git push